version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
aliases:
  - &workdir
    working_directory: ~/repo

  - &docker-node
    docker:
      - image: cimg/node:18.20.4
  
  - &attach-workspace
    attach_workspace:
      at: ~/repo

  - &persist-workspace
    persist_to_workspace:
      root: ~/repo
      paths:
        - '*'
workflows:
  jobs:
    build_and_push:
      <<: *docker-node
      <<: *workdir
      steps:
        - *attach-workspace
        - checkout  # Checkout the source code
        - run:
            name: Login to AWS ECR
            command: |
              aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com
  
        - aws-ecr/build-and-push-image:
            context: aws-dev
            create-repo: true
            dockerfile: Dockerfile
            path: .
            repo: circleci-ecr-demo-source
            tag: "${CIRCLE_SHA1}"
