version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3

jobs:
  build_and_push_image:
    jobs:
      docker:
        - image: circleci/python:3.8
      working_directory: ~/repo
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Login to AWS ECR
            command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 703060810297.dkr.ecr.us-east-1.amazonaws.com
      - aws-ecr/build-and-push-image:
          context: aws-dev
          create-repo: true
          dockerfile: Dockerfile
          path: .
          repo: circleci-ecr-demo-source
          tag: "${CIRCLE_SHA1}"

workflows:
  build_and_push_image:
    jobs:
      - build_and_push_image
