version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.0.0

jobs:
  push_ecr:
    machine:
      image: ubuntu-2004:202111-02
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - aws-ecr/build-and-push-image:
          repo: circleci-ecr-demo
          tag: "${CIRCLE_SHA1}"    
workflows:
  version: 2
  circle-ecr:
    jobs:
      - push_ecr:
          context:
            - aws-dev
          filters:
            branches:
              only:
                - main
